### ISSUE TITLE
Mods will not deploy or purge

### ISSUE THREAD

**Issue by yaboipancake** [Nexus-Mods/discord-bot#29]
Hi all, about two days ago i had been modding Fallout 4 perfectly fine using Vortex mod manager and the Nexus mods website until the mod "Rebuild red rocket" updated, using the check for updates in the mods folder and the error code that keeps appearing is the phrase:

Failed to parse manifest : "Unexpected token ", " " ... is not valid JSON
Backup couldnt be read: ENOENT: no such file or directory, open D:\Vortex Mods\vortex.deployment.dinput.json

Edit: Ive uninstalled and reinstalled vortex twice and i haven't uninstalled FO4 yet

for further details 

Failed to parse manifest: "Unexpected token '', ""... is not valid JSON"
Backup couldn't be read: ENOENT: no such file or directory, open 'D:\Vortex Mods\vortex.deployment.dinput.json'
Error: Failed to parse manifest: "Unexpected token '', ""... is not valid JSON"
    at readManifest (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5259:67)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5265:90
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
Prior Context:
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9931:16
    at withActivationLock (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5288:227)
    at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:4841:232
    at tryCatcher (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)

**Comment by Pickysaurus** [comment]
This tracker is for the Discord bot.
